name: build

on:
  workflow_dispatch
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Install prerequisites
        run: |
          sudo apt install -y flex bison libicu-dev libperl-dev tcl krb5-multidev
      - name: Checkout code
        uses: actions/checkout@v4
      - name: build
        run: |
          chmod +x ./configure
          ./configure --without-readline
          make world-bin
          su
          make install
      - name: "Upload files"
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          path: /usr/local/pgsql
          name: pgsql
