name: build

on:
  workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing flex bison libicu-dev libperl-dev tcl krb5-multidev \
          debhelper-compat dh-exec docbook-xsl gdb gettext dpkg-dev \
          libio-pty-perl libipc-run-perl libkrb5-dev libldap2-dev libpam-dev \
          libreadline-dev libselinux1-dev libssl-dev libsystemd-dev build-essential \
          libxml2-dev libxml2-utils libxslt1-dev pkg-config clang llvm-dev \
          python3-dev systemtap-sdt-dev tcl-dev uuid-dev xsltproc libz-dev
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: REL_17_STABLE
#      - name: build
#        run: |
#          echo "::group::Configure"
#          chmod +x ./configure
#          ./configure --without-readline
#          echo "::endgroup::"
#          echo "::group::Make"
#          make world-bin
#          echo "::endgroup::"
#          echo "::group::Install"
#          sudo make install
#          echo "::endgroup::"
      - name: "Get Debian PostgreSQL’s package generator scripts"
        run: |
          mkdir -p ./deb && cd ./deb
          git clone https://salsa.debian.org/postgresql/postgresql.git
          cp ./postgresql/debian ../ -rf
          cd ..
          dpkg-buildpackage -rfakeroot -b -uc -us
      - name: Upload deb packages
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          path: ./*.deb
          name: pgsql-deb
#  build-deb:
#    needs: build
#    runs-on: ubuntu-latest
#    steps:
#      - name: Install prerequisites
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y --fix-missing flex bison libicu-dev libperl-dev tcl krb5-multidev \
#          debhelper-compat dh-exec docbook-xsl gdb gettext dpkg-dev \
#          libio-pty-perl libipc-run-perl libkrb5-dev libldap2-dev libpam-dev \
#          libreadline-dev libselinux1-dev libssl-dev libsystemd-dev build-essential \
#          libxml2-dev libxml2-utils libxslt1-dev pkg-config clang llvm-dev \
#          python3-dev systemtap-sdt-dev tcl-dev uuid-dev xsltproc libz-dev
#      - name: Download artifact
#        uses: actions/download-artifact@v4
#      - name: "Get Debian PostgreSQL’s package generator scripts"
#        run: |
#          git clone https://salsa.debian.org/postgresql/postgresql.git
#          cp ./postgresql/debian ./ -rf
#          dpkg-buildpackage -rfakeroot -b -uc -us
#      - name: Upload deb packages
#        uses: actions/upload-artifact@v4
#        with:
#          include-hidden-files: true
#          path: /usr/local/pgsql/**/*.deb
#          name: pgsql-deb
